---
gating_overrides_file: "{{ lookup('env', 'WORKSPACE') }}/user_zzz_gating_variables.yml"
gating_overrides:
  apply_security_hardening: false
  maas_fqdn_extension: ".{{ lookup('env', 'NODE_NAME') }}"
  memory_used_percentage_warning_threshold: 99.0
  memory_used_percentage_critical_threshold: 99.5
  net_max_speed: 1000
  lb_name: "{{ lookup('env', 'NODE_NAME') }}"
  maas_external_ip_address: "{{ ansible_default_ipv4.address }}"
  tempest_testr_opts:
    - '--concurrency 3'
  tempest_run_tempest_opts: []
  # The MNAIO tool gives different VMs different amounts of RAM, but seeing as
  # our OnMetal machines have ample RAM we bump this across the board for all
  # VMs
  server_vm_ram: 16384
